[package]
name = "cargo-profiler"
version = "0.2.0"
authors = ["pegasos1", "Sven-Hendrik Haase <svenstaro@gmail.com>"]
description = "Cargo subcommand to profile your applications."
homepage = "http://github.com/svenstaro/cargo-profiler"
repository = "http://github.com/svenstaro/cargo-profiler"
license = "MIT"
keywords = ["cargo", "profiler", "subcommand", "valgrind", "performance"]

[dependencies]
clap = "2.5.1"
regex = "1"
ndarray = "0.12"
lazy_static = "0.2.1"
rustc-serialize = "0.3"

[lib]
name="profiler"
lib="src/lib.rs"

[[bin]]
name = "cargo-profiler"
bin='src/main.rs'
